language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_0c07d9c21c4a_key -iv $encrypted_0c07d9c21c4a_iv -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- ssh-add id_rsa
script:
- npm run build
- npm test
deploy:
- provider: script
  skip_cleanup: true # do not delete the built assets
  script: npm run deploy
  on:
    branch: source
